### ISSUE TITLE
Automate building of docker image

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/jenkins-docker#2]
@CAMOBAP795 or @phuonghuynh would you have time to make Travis build/update this docker image? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse let me have a look

**Comment by CAMOBAP** [comment]
@ronaldtse PR is ready locally, please:
 - give me write access for this repo
 - enable travis for this repo
 - configure `DOCKER_LOGIN_USERNAME`, `DOCKER_LOGIN_PASSWORD` on travis

**Comment by CAMOBAP** [comment]
Looks like there is some issues with DOCKER_* secure variables

```
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
```

@ronaldtse may I ask you to double check ?

**Comment by CAMOBAP** [comment]
@ronaldtse looks fixed now, thanks

**Comment by ronaldtse** [comment]
Yes I just fixed the authentication bit. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 so it's building the image but not pushing it. Why does the code write:

```
$ if [[ -n "$TRAVIS_TAG" ]]; then
      make tp ;
    fi
```

**Comment by ronaldtse** [comment]
P.S. I've pushed a new commit waiting for it to push.

**Comment by CAMOBAP** [comment]
@ronaldtse tag need to be pushed to activate make tp

**Comment by CAMOBAP** [comment]
let me do this

**Comment by CAMOBAP** [comment]
Let's wait for https://travis-ci.com/riboseinc/jenkins-docker/builds/106863638

To do tag you need
```
git tag v2.170`
git push origin master --tags
```

**Comment by ronaldtse** [comment]
@CAMOBAP795 the Makefile already does that:
```
make tp
```

Runs exactly that.

**Comment by ronaldtse** [comment]
@CAMOBAP795 `make tp` is used for tagging the docker image, not at git.

**Comment by ronaldtse** [comment]
I guess you can consider it as a "deployment step" in Travis.

**Comment by CAMOBAP** [comment]
Generally you right, I remember that I tried to accomplish the same with `deploy:` but it didn't worked (I don't remember why exactly)

Let me try

**Comment by CAMOBAP** [comment]
["If your deployment needs more customization than the `after_success` method allows, use a custom script."](https://docs.travis-ci.com/user/deployment/script/)

Anyway I have prepared PR to use deploy https://github.com/riboseinc/jenkins-docker/pull/4

**Comment by CAMOBAP** [comment]
Done
